// This file is automatically generated. Do not edit it directly.
// Supabase has been replaced with a custom Node.js API backend
// This file is kept for compatibility but exports empty objects

export const supabase = {
  // Placeholder for removed Supabase client
  // All database operations now use the custom API at http://localhost:5001/api
};