// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fypwyfkdwjeunrediyww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5cHd5Zmtkd2pldW5yZWRpeXd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzI1MDUsImV4cCI6MjA2ODE0ODUwNX0.e7SX9hIohJDRC8wsDdXVNa9IuSxLQkAQ-087wlYWQZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});